stages:
  - build
  - linter
  - test
  - deploy

build-job:
  stage: build
  script:
    - rm -rf artifacts
    - mkdir artifacts
    - (cd src/cat && make build)
    - (cd src/grep && make build)
    - cp src/cat/s21_cat src/grep/s21_grep artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  only:
    - develop
  after_script:
    - telegrambot_send_message.sh $(CI_JOB_NAME)

linter-job:
  stage: linter
  script:
    - cp materials/linters/.clang-format src/cat
    - cp materials/linters/.clang-format src/grep
    - clang-format -n -Werror src/cat/*.[ch]
    - clang-format -n -Werror src/grep/*.[ch]
    - rm -rf src/cat/.clang-format src/grep/.clang-format
    - (cd src/cat && make leaks)
    - (cd src/grep && make leaks)
  only:
    - develop
  after_script:
    - telegrambot_send_message.sh $(CI_JOB_NAME)

test-job:
  stage: test
  script:
    - (cd src/cat && make test)
    - (cd src/cat && make clean)
    - (cd src/grep && make test)
    - (cd src/grep && make clean)
  only:
    - develop
  after_script:
    - telegrambot_send_message.sh $(CI_JOB_NAME)


# deploy-job:
#   stage: deploy
#   script:
