stages:
  - build
  - linter
  - test

build-job:
  stage: build
  script:
    - rm -rf artifacts
    - mkdir artifacts
    - (cd src/cat && make build)
    - (cd src/grep && make build)
    - cp src/cat/s21_cat src/grep/s21_grep artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  only:
    - develop

linter-job:
  stage: linter
  script:
  - cp materials/linters/.clang-format src/cat
  - cp materials/linters/.clang-format src/grep
  - clang-format -n -Werror src/cat/*.[ch]
  - clang-format -n -Werror src/grep/*.[ch]